package oepnv.stations;

public enum B230Station implements BusStation {
    ISMANING,
    ISMANING_GEROLDSTRASSE,
    ISMANING_OSTERFELDSTRASSE,
    ISMANING_MAX_VON_EYTH_STRASSE,
    GARCHING_WASSERTURMSTRASSE,
    GARCHING_AUWEG,
    GARCHING,
    GARCHING_LEHRER_STIEGLITZ_STRASSE,
    GARCHING_UNTERE_STRASSAECKER,
    GARCHING_LUDWIG_PRANDTL_STRASSE,
    GARCHING_BOLTZMANNSTRASSE,
    GARCHING_FORSCHUNGSZENTRUM
}
