package oepnv.Stations;

public enum B292Stations implements BusStation {
    GARCHING_FORSCHUNGSZENTRUM,
    GARCHING_LICHTENBERGSTRASSE,
    GARCHING_BOLTZMANNSTRASSE,
    GARCHING_LUDWIG_PRANDTL_STRASSE,
    GARCHING_LEHRER_STIEGLITZ_STRASSE,
    GARCHING,
    GARCHING_MAIER_LEIBNITZ_STRASSE,
    GARCHING_KELTENWEG,
    GARCHING_PARKRING_SUED,
    GARCHING_PARKRING_WEST,
    GARCHING_DAIMLERSTRASSE,
    GARCHING_HOCHBRUECK,
    GARCHING_GEWERBEGEBIET,
    HOCHBRUECK_VOITHSTRASSE,
    HOCHBRUECK_CARL_VON_LINDE_STRASSE,
    HOCHBRUECK_HOHE_BRUECKEN_STRASSE,
    LUSTHEIM,
    OBERSCHLEISSHEIM_SCHLOSS,
    OBERSCHLEISSHEIM_MITTENHEIMER_STRASSE,
    OBERSCHLEISSHEIM,
    OBERSCHLEISSHEIM_AM_STUTENANGER,
    OBERSCHLEISSHEIM_ST_MARGARETHEN_STRASSE,
    OBERSCHLEISSHEIM_VETERINAERSTRASSE,
    OBERSCHLEISSHEIM_SONNENSTRASSE
}
