package oepnv.stations;

public enum B690Station implements BusStation {
        ECHING_BLUETENSTRASSE,
        ECHING_BAHNHOFSTRASSE,
        ECHING_OTTOSTRASSE,
        ECHING_HOTEL_OLYMP,
        ECHING_SCHLESIERSTRASSE,
        ECHING_OST,
        ECHING_OHMSTRASSE,
        ECHING_LIEBIGSTRASSE,
        ECHING_FRAUNHOFERSTRASSE,
        NEUFAHRN_ZEPPELINSTRASSE,
        NEUFAHRN_CHRISTL_CRANZ_STRASSE,
        NEUFAHRN_BAHNHOFSTRASSE,
        NEUFAHRN_RATHAUS,
        NEUFAHRN,
        NEUFAHRN_ALTE_KIRCHE,
        NEUFAHRN_LENA_CHRIST_STRASSE,
        DIETERSHEIM_ECHINGER_STRASSE,
        GARCHING_LUDWIG_PRANDTL_STRASSE,
        GARCHING_BOLTZMANNSTRASSE,
        GARCHING_FORSCHUNGSZENTRUM,
        GARCHING_LICHTENBERGSTRASSE

}
