package oepnv.stations;

public enum S1Station implements SBahnStation {
    FREISING,
    PULLING,
    FLUGHAFEN_MUENCHEN,
    FLUGHAFEN_BESUCHERPARK,
    NEUFAHRN,
    ECHING,
    LOHHOF,
    UNTERSCHLEISSHEIM,
    OBERSCHLEISSHEIM,
    FELDMOCHING,
    FASANERIE,
    MOOSACH,
    LAIM,
    HIRSCHGARTEN,
    DONNERSBERGERBRUECKE,
    HACKERBRUECKE,
    HAUPTBAHNHOF,
    KARLSPLATZ_STACHUS,
    MARIENPLATZ,
    ISARTOR,
    ROSENHEIMER_PLATZ,
    OSTBAHNHOF,
    LEUCHTENBERGRING
}
