package oepnv.Stations;

public enum U3Station implements UBahnStation {
    MOOSACH,
    MOOSACHER_ST_MARTINS_PLATZ,
    OLYMPIA_EINKAUFSZENTRUM,
    OBERWIESENFELD,
    OLYMPIAZENTRUM,
    PETUELRING,
    SCHEIDPLATZ,
    BONNER_PLATZ,
    MUENCHNER_FREIHEIT,
    GISELASTRASSE,
    UNIVERSITAET,
    ODEONSPLATZ,
    MARIENPLATZ,
    SENDLINGER_TOR,
    GOETHEPLATZ,
    POCCISTRASSE,
    IMPLERSTRASSE,
    BRUDERMUEHLSTRASSE,
    THALKIRCHEN,
    OBERSENDLING,
    AIDENBACHSTRASSE,
    MACHTLFINGER_STRASSE,
    FORSTENRIEDER_ALLEE,
    BASLER_STRASSE,
    FUERSTENRIED_WEST
}
