package oepnv.Stations;

public enum X201Station implements BusStation {
    DACHAU_BAHNHOF,
    OBERSCHLEISSHEIM_REGATTAANLAGE,
    OBERSCHLEISSHEIM_VETERINAERSTRASSE,
    HOCHBRUECK_VOITHSTRASSE,
    GARCHING_HOCHBRUECK,
    GARCHING_FORSCHUNGSZENTRUM
}
