package oepnv.Stations;

public enum X660Station implements BusStation {
    FREISING_WEIHENSTEPHAN,
    FREISING,
    FREISING_SCHLUETERSTRASSE,
    ACHERING_ACHERINGER_HAUPTSTRASSE,
    MINTRACHING_MUENCHNER_STRASSE,
    DIETERSHEIM_AUWEG,
    GARCHING_FORSCHUNGSZENTRUM
}
