package oepnv;

public enum Reason {
    VERDI_STRIKE,
    GDL_STRIKE,
    SNOWFALL,
    RAIN,
    SUNSHINE,
    LACK_OF_DRIVERS,
    DELAY_OF_PREVIOUS_TRAIN,
    PERSONS_ON_TRACKS,
    CABLE_DAMAGE,
    SWITCH_DAMAGE,
    DOOR_DAMAGE,
    SIGNAL_DISTURBANCE,
    NO_REASON
}
